sudo: required
services: docker
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - export ATSD_LOGIN=axibase
  - export ATSD_PASSWORD=axibase
install:
  - docker run -d --name="atsd-api-test-python" -e axiname="$ATSD_LOGIN" -e axipass="$ATSD_PASSWORD" -e timezone="Asia/Kathmandu" -p8443:8443 -p8088:8088 axibase/atsd:api_test
  - pip install .
  - wget https://raw.githubusercontent.com/axibase/atsd/master/.travis-functions.sh && source .travis-functions.sh
  - install_checkers_in_non_doc_project
  - while [[ $(curl --user $ATSD_LOGIN:$ATSD_PASSWORD --write-out %{http_code} --silent --output /dev/null http://localhost:8088/version) != 200 ]]; do  echo "waiting to start ATSD server ..."; sleep 3; done
script:
  - pip list
  - python -m unittest discover -v tests
  - spellcheck
  - linkcheck
  - stylecheck
  - validate_anchors
cache: pip
notifications:
  webhooks: https://apps.axibase.com/api/v1/messages/wk-travis-ci/travis-ci?json.parse=payload&exclude=payload.id;payload.number;payload.config*;payload.repository*;payload.matrix*;payload.*commit*;payload.status_message;payload.result&include=payload.repository.name&command.message=payload.result_message
