sudo: required
services: docker
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - docker run -d --name="atsd-api-test-python" -e axiname="axibase" -e axipass="axibase" -e timezone="Asia/Kathmandu" -p8443:8443 -p8088:8088 axibase/atsd:api_test
  - pip install .
  - wget https://raw.githubusercontent.com/axibase/atsd/master/.travis-functions.sh && source .travis-functions.sh
  - install_checkers_in_non_doc_project
script:
  - python test.py
  - spellcheck
  - linkcheck
  - stylecheck
cache: pip
